from app.data.ngo_links import NGO_DONATION_URLS
from app.ingestion.models import CrisisConfig, NgoConfig, NgoSourceConfig


CRISES = [
    CrisisConfig(
        id="afghanistan",
        name="Afghanistan",
        country="Afghanistan",
        iso3="AFG",
        lat=33.8,
        lng=66.1,
        crisis_type="Complex emergency",
        focus_areas=["Food security", "Health", "Shelter", "Livelihoods"],
        affected_locations=["Herat", "Kabul", "Kandahar", "Badghis", "Nangarhar"],
        summary="Economic hardship, climate shocks, displacement, and pressure on essential services continue to shape humanitarian needs.",
        plan_page_url="https://reliefweb.int/country/afg",
        displacement_page_url="https://www.unhcr.org/where-we-work/countries/afghanistan",
    ),
    CrisisConfig(
        id="sahel",
        name="Central Sahel",
        country="Mali",
        iso3="MLI",
        lat=16.4,
        lng=-3.6,
        crisis_type="Conflict and regional displacement",
        focus_areas=["Protection", "Food security", "Livelihoods", "Shelter"],
        affected_locations=["Mali", "Burkina Faso", "Niger"],
        summary="Conflict, insecurity, climate pressure, and displacement are affecting communities across the Central Sahel.",
        plan_page_url="https://reliefweb.int/country/mli",
        displacement_page_url="https://www.unhcr.org/emergencies/sahel-crisis",
    ),
    CrisisConfig(
        id="drc",
        name="Eastern DRC",
        country="Dem. Rep. Congo",
        iso3="COD",
        lat=-3.4,
        lng=27.2,
        crisis_type="Armed conflict and displacement",
        focus_areas=["Protection", "Shelter", "Health", "Food security"],
        affected_locations=["North Kivu", "South Kivu", "Ituri", "Tanganyika"],
        summary="Armed violence and repeated displacement have disrupted services and increased protection, shelter, health, and food needs.",
        plan_page_url="https://reliefweb.int/country/cod",
        displacement_page_url="https://www.unhcr.org/where-we-work/countries/democratic-republic-congo",
    ),
    CrisisConfig(
        id="gaza",
        name="Gaza",
        country="Palestine",
        iso3="PSE",
        lat=31.45,
        lng=34.4,
        crisis_type="Armed conflict and displacement",
        focus_areas=["Health", "Food", "Shelter", "Water and sanitation"],
        affected_locations=["North Gaza", "Gaza City", "Deir al-Balah", "Khan Younis", "Rafah"],
        summary="Hostilities and access constraints have severely affected health care, shelter, food security, water systems, and civilian protection.",
        plan_page_url="https://www.ochaopt.org/",
        displacement_mode="none",
    ),
    CrisisConfig(
        id="bangladesh",
        name="Rohingya response",
        country="Bangladesh",
        iso3="BGD",
        lat=21.42,
        lng=92.0,
        crisis_type="Refugee displacement",
        focus_areas=["Protection", "Food", "Shelter", "Health"],
        affected_locations=["Cox's Bazar", "Bhasan Char"],
        summary="The protracted Rohingya response requires continued support for refugees and affected host communities.",
        plan_page_url="https://reliefweb.int/country/bgd",
        displacement_page_url="https://data.unhcr.org/en/situations/myanmar_refugees",
        displacement_mode="coa",
    ),
    CrisisConfig(
        id="somalia",
        name="Somalia",
        country="Somalia",
        iso3="SOM",
        lat=5.2,
        lng=46.2,
        crisis_type="Climate shocks and displacement",
        focus_areas=["Water", "Food security", "Livelihoods", "Protection"],
        affected_locations=["Banadir", "Bay", "Lower Shabelle", "Gedo", "Hiraan"],
        summary="Recurrent drought, flooding, conflict, and displacement continue to affect access to food, water, livelihoods, and protection.",
        plan_page_url="https://reliefweb.int/country/som",
        displacement_page_url="https://www.unhcr.org/where-we-work/countries/somalia",
    ),
    CrisisConfig(
        id="sudan",
        name="Sudan",
        country="Sudan",
        iso3="SDN",
        lat=15.5,
        lng=30.2,
        crisis_type="Armed conflict and displacement",
        focus_areas=["Food security", "Protection", "Shelter", "Health"],
        affected_locations=["Darfur", "Khartoum", "Kordofan", "Gezira"],
        summary="Conflict has driven mass displacement, disrupted essential services, and increased food insecurity across Sudan and neighbouring countries.",
        plan_page_url="https://reliefweb.int/country/sdn",
        displacement_page_url="https://www.unhcr.org/emergencies/sudan-emergency",
    ),
    CrisisConfig(
        id="yemen",
        name="Yemen",
        country="Yemen",
        iso3="YEM",
        lat=15.6,
        lng=47.5,
        crisis_type="Protracted conflict",
        focus_areas=["Food security", "Nutrition", "Health", "Protection"],
        affected_locations=["Marib", "Al Hudaydah", "Taiz", "Hajjah", "Sa'dah"],
        summary="Conflict, economic decline, climate shocks, and disrupted public services continue to drive humanitarian needs.",
        plan_page_url="https://reliefweb.int/country/yem",
        displacement_page_url="https://www.unhcr.org/where-we-work/countries/yemen",
    ),
]


NGOS = [
    NgoConfig(
        id="care",
        initials="CA",
        short_name="CARE",
        name="CARE",
        descriptor="Global humanitarian and development organization",
        founded_year=1945,
        accent="#b95d3d",
        accepted_giving_types=["General donation"],
        focus_areas=["Food", "Health", "Livelihoods", "Gender equality", "Emergency response"],
        donation_url=NGO_DONATION_URLS["care"],
        baseline={
            "reporting_year": 2025,
            "reported_reach": "58.7M people",
            "countries_active": 121,
            "reported_activity": "1,467 projects",
            "annual_income": None,
            "annual_expenditure": None,
        },
        source=NgoSourceConfig(
            title="CARE 2025 Annual Report",
            source_type="Official annual report",
            url="https://www.care.org/resources/care-2025-annual-report/",
            reporting_year=2025,
            parser="care",
        ),
    ),
    NgoConfig(
        id="human-appeal",
        initials="HA",
        short_name="Human Appeal",
        name="Human Appeal",
        descriptor="Humanitarian and development organization",
        founded_year=1991,
        accent="#d8893d",
        accepted_giving_types=["Zakat", "Sadaqah", "General donation"],
        focus_areas=["Food", "Health", "Shelter", "Water", "Orphan support"],
        donation_url=NGO_DONATION_URLS["human-appeal"],
        baseline={
            "reporting_year": 2024,
            "reported_reach": "6.24M people",
            "countries_active": 30,
            "reported_activity": "Emergency, development, and seasonal projects",
            "annual_income": "GBP 90.2M",
            "annual_expenditure": "GBP 83.3M",
        },
        source=NgoSourceConfig(
            title="Human Appeal Annual Report 2024",
            source_type="Official annual report",
            url="https://humanappeal.org.uk/media/l51oprl5/a201-human-appeal_annual-report-2024-charity-commission.pdf",
            reporting_year=2024,
            parser="human_appeal",
        ),
    ),
    NgoConfig(
        id="islamic-relief",
        initials="IR",
        short_name="Islamic Relief",
        name="Islamic Relief Worldwide",
        descriptor="Faith-based humanitarian and development organization",
        founded_year=1984,
        accent="#167b66",
        accepted_giving_types=["Zakat", "Sadaqah", "General donation"],
        focus_areas=["Food", "Shelter", "Health", "Water", "Livelihoods", "Protection"],
        donation_url=NGO_DONATION_URLS["islamic-relief"],
        baseline={
            "reporting_year": 2024,
            "reported_reach": "14.5M people",
            "countries_active": 38,
            "reported_activity": "266 emergency projects in 28 countries",
            "annual_income": "GBP 275.6M",
            "annual_expenditure": "GBP 303.8M",
        },
        source=NgoSourceConfig(
            title="Islamic Relief Worldwide Annual Report 2024",
            source_type="Official annual report",
            url="https://annualreport.islamic-relief.org/2024/wp-content/uploads/2025/07/IRW-AR2024-FINAL-14072025.pdf",
            reporting_year=2024,
            parser="islamic_relief",
        ),
    ),
    NgoConfig(
        id="mercy-corps",
        initials="MC",
        short_name="Mercy Corps",
        name="Mercy Corps",
        descriptor="Global humanitarian and resilience organization",
        founded_year=1979,
        accent="#327fa1",
        accepted_giving_types=["General donation"],
        focus_areas=["Food", "Water", "Livelihoods", "Cash assistance", "Climate resilience"],
        donation_url=NGO_DONATION_URLS["mercy-corps"],
        baseline={
            "reporting_year": 2025,
            "reported_reach": "37M people",
            "countries_active": 35,
            "reported_activity": "Humanitarian and resilience programmes",
            "annual_income": None,
            "annual_expenditure": None,
        },
        source=NgoSourceConfig(
            title="Mercy Corps 2025 Annual Impact Report",
            source_type="Official annual impact report",
            url="https://www.mercycorps.org/annual-reports/2025",
            reporting_year=2025,
            parser="mercy_corps",
        ),
    ),
    NgoConfig(
        id="save-the-children",
        initials="SC",
        short_name="Save the Children",
        name="Save the Children International",
        descriptor="Child-focused humanitarian and development organization",
        founded_year=1919,
        accent="#c64132",
        accepted_giving_types=["General donation"],
        focus_areas=["Child protection", "Health", "Nutrition", "Education", "Emergency response"],
        donation_url=NGO_DONATION_URLS["save-the-children"],
        baseline={
            "reporting_year": 2025,
            "reported_reach": "37.8M children",
            "countries_active": 92,
            "reported_activity": "113 emergencies responded to",
            "annual_income": None,
            "annual_expenditure": None,
        },
        source=NgoSourceConfig(
            title="Save the Children 2025 Impact",
            source_type="Official impact page",
            url="https://www.savethechildren.net/",
            reporting_year=2025,
            parser="save_the_children",
        ),
    ),
]


CRISIS_ALIASES = {
    "afghanistan": [r"\bAfghanistan\b"],
    "sahel": [r"\bMali\b", r"\bSahel\b"],
    "drc": [r"\bDRC\b", r"Democratic Republic of (?:the )?Congo", r"\bCongo\b"],
    "gaza": [r"\bGaza\b", r"Palestinian territor"],
    "bangladesh": [r"\bBangladesh\b", r"\bRohingya\b"],
    "somalia": [r"\bSomalia\b"],
    "sudan": [r"(?<!South )\bSudan\b"],
    "yemen": [r"\bYemen\b"],
}


# CARE blocks automated requests, so current country pages provide the initial evidence links.
CARE_CRISIS_EVIDENCE = {
    "afghanistan": "https://www.care.org/our-work/where-we-work/afghanistan/",
    "sahel": "https://www.care.org/our-work/where-we-work/mali/",
    "drc": "https://www.care.org/our-work/where-we-work/democratic-republic-of-the-congo/",
    "gaza": "https://www.care.org/our-work/where-we-work/west-bank-and-gaza/",
    "somalia": "https://www.care.org/our-work/where-we-work/somalia/",
    "sudan": "https://www.care.org/our-work/where-we-work/sudan/",
}
